DELETE FROM books_id_genres_id WHERE TRUE;
DELETE FROM books_id_authors_id WHERE TRUE;
DELETE FROM genres WHERE TRUE;
DELETE FROM authors WHERE TRUE;
DELETE FROM books WHERE TRUE;
DROP SEQUENCE genre_seq;
DROP SEQUENCE author_seq;
DROP SEQUENCE book_seq;